export const ICON_NAMES = {
  HIDE: 'eye',
  SHOW: 'eye-off',
  BACK: 'arrow-back',
  CHECKMARK_CIRCLE: 'checkmark-circle',
  CHECKMARK: 'checkmark',
  CHECKBOX: 'checkbox',
  CHECKBOX_OUTLINE: 'square-outline',
  HOME: 'home',
  HOME_OUTLINE: 'home-outline',
  PERSON: 'person-circle',
  PERSON_OUTLINE: 'person-circle-outline',
  SEARCH: 'search',
  SEARCH_OUTLINE: 'search-outline',
} as const;
